import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"
